### PR TITLE
Add `@mobily/re-date`

### PR DESCRIPTION
**Pull request by mobily**
This PR adds [`@mobily/re-date`](https://github.com/mobily/re-date).

### CODE REVIEW

**Comment by glennsl** [comment]
Thanks!

This looks like it could easily be made platform-independent, since you don't use any `external`s. All you need to do is not rely on bucklescript-specific features such as `bs.deriving` and the fast pipe (`->`) which isn't a great idea to use anyway.

I'll merge it as-is now, but let me know if you make it platform-independent and want me to change the entry for it.

**Comment by mobily** [comment]
@glennsl thank you! 😊 

> All you need to do is not rely on bucklescript-specific features such as bs.deriving and the fast pipe (->) which isn't a great idea to use anyway.

if you had free time, could you write up why it's not a good idea to use the fast pipe?

**Comment by glennsl** [comment]
Apart from unnecessarily restricting your code to a specific platform, it's not so much the use of the fast pipe itself in isolation that's a problem, so much as its impact on the overall code base and ecosystem.

The fast pipe isn't very useful unless you have functions specifically designed to be used with it, and while this won't make the functions strictly incompatible with other platforms, they'll be much less convenient to use without the fast pipe, since that convenience is the reason we want any pipe operator in the first place. But they're also less useful even WITH the fast pipe since you can't compose these functions using partial function application the same way you can if the "target" is the last argument. That's the reason why "t last" and the standard pipe operator (`|>`) is the convention in every other functional language, including OCaml.

For example, with the standard pipe and t last you can write

    listOfOptions |> List.map(Option.getWithDefault(defaultValue))

and with the fast pipe you'd have to write

    listOfOption->List.map(item => item->Option.getWithDefault(defaultValue))

which might not seem too bad with this simple example, but if you intend to do proper functional programming this will add up to a significant amount of noise.

Then, unless you only use libraries with functions that are all designed for the same pipe operator, you'll have to keep in mind which kind of function you're dealing with and which pipe operator to use with it, often juggling both in the same function call chain. If you instead try to standardize on the fast pipe, that means you'll have to avoid using any platform-agnostic libraries. If you make libraries and bindings designed for the fast pipe you make the ecosystem worse for those of us not using it. And since the fast pipe is a very recent additions, with not a lot of libraries designed for it yet, it seems to make a lot more sense to just not use it, and try to encourage others to not use it either.

I hope this makes sense :)

**Comment by mobily** [comment]
it does make sense! thank you for excellent, in-depth explanation 😊 I'm going to remove the `fast pipe` syntax as soon as possible and make it platform-independent

**Comment by mobily** [comment]
@glennsl all bucklescript-specific features are removed, could you confirm it's platform-independent now? :)

https://github.com/mobily/re-date/blob/master/src/ReDate.re

**Comment by glennsl** [comment]
Hmm, sorry, I see now that you have `open Js` at the top and use several `Js` modules. I didn't think you did since I didn't see any `Js.*` modules used, but the heavy use of those modules make it pretty platform-dependent. There's also some 'Belt' usage that is BuckleScript-specific, at least for now, but that's comparatively minor.

It's usually not a good idea to open modules at file level, unless they were specifically designed for it, since it makes it difficult to identify modules and pollutes the namespace. See more about it [here](https://ocaml.org/learn/tutorials/guidelines.html#How-to-use-modules).

Apologies for leading you astray, and thanks for trying to follow my bad advice at least :) I hope it wasn't too much work, but I do think your code slightly clearer and better now.

**Comment by mobily** [comment]
> I hope it wasn't too much work, but I do think your code slightly clearer and better now.

@glennsl an hour or two 😅 but no worries, it was a valuable lesson for me, and I also feel the code is much cleaner right now

thank you for posting the link to the OCaml docs, I will definitely read it :)

**Pull request merged**
