### PR TITLE
Add bs-fluture

### PR DESCRIPTION
**Pull request by benadamstyles**
https://github.com/benadamstyles/bs-fluture
https://www.npmjs.com/package/bs-fluture

### CODE REVIEW

**Comment by glennsl** [comment]
Thanks! Could you add a usage example to the Readme and publish it in a new patch release? I'll merge when you say it's done.

**Comment by benadamstyles** [comment]
Cheers, I'll do this now. I have one question – should the `lib` folder be included in the `npm` package? Can't get my head around it!

**Comment by benadamstyles** [comment]
Just published the package with an update readme. Kept the `lib` folder in for now – if I should exclude it, just let me know and I'll push an update. Thanks!

**Comment by glennsl** [comment]
Thanks! There can be problems with including the `lib` folder if it's consumed by code that is compiled with a different version of `bs-platform`. See https://github.com/glennsl/bs-json/issues/33 for an example. So unless you're specifically targeting js consumers, it's probably better to leave it out.

**Pull request merged**
