### PR TITLE
Add bs-mysql2 bindings.

### PR DESCRIPTION
**Pull request by scull7**

### CODE REVIEW

**Comment by glennsl** [comment]
Thanks! What's the difference between this and `mysql.js`? It would be nice to have that documented up front, to make it easier to choose.

**Comment by scull7** [comment]
This one uses the [node-mysql2] which has more features such as `named placeholders`. The link will take you to their [History and Why MySQL2][node-mysql2] section.


[node-mysql2]: https://github.com/sidorares/node-mysql2#history-and-why-mysql2

**Comment by scull7** [comment]
README updated with [Why?](https://github.com/scull7/bs-mysql2#why) section.

**Comment by glennsl** [comment]
On the surface this looks more like a status section. Looking more carefully I can see it's the bullet points from the page you linked to, but that's not very apparent from just reading your readme. Or even after having read the page you linked, really. It would be nice if it explained that these are features that are not in bs-mysql/mysqljs. Otherwise looks great :)

**Comment by scull7** [comment]
Updated the [Why?][why] section, hopefully, it is more clear now.

[why]: https://github.com/scull7/bs-mysql2#why

**Comment by glennsl** [comment]
That looks great! Thank you :)

**Pull request merged**
