### PR TITLE
Add @justgage/reason-cookie

### PR DESCRIPTION
**Pull request by justgage**
This is my library that wraps js-cookie: https://github.com/justgage/reason-cookie

### CODE REVIEW

**Comment by glennsl** [comment]
Hey. You're missing the repository url in package.json. Could you add that?

**Comment by justgage** [comment]
Thanks for the feedback! Yeah go ahead and change these.

`<bikeshedding>`
I find the distinction between libraries and bindings a bit odd, mostly because this library _could_ be rewritten to not use the JS library underneath without changing the API.
`</bikeshedding>`

Thanks so much for taking a look at this. I'm excited to add my library to the ecosystem 🎉

**Comment by glennsl** [comment]
There's definitely a large gray area in the intersection of libraries and bindings, but I think this is pretty clearly a binding. Primarily because it consists solely of externals and mirrors an existing js library API, which is what really matters from a user POV, but you also wouldn't be able to rewrite it completely in reason, since the underlying library uses browser APIs that you'd have to bind to instead.

I see you do have the repository url in the package manifest that's in the repository, but you haven't published it. Could you do that?

**Comment by justgage** [comment]
Good point. @glennsl I think I've done what you asked. However I'm not 100% sure.

**Comment by justgage** [comment]
I went ahead and made the changes you talked about ✍️

**Comment by glennsl** [comment]
Looks good, thanks! :)

**Comment by justgage** [comment]
@glennsl It seems that my package isn't showing up on redex. Also it seems that the recent releases is kinda gone? Maybe it just takes a while to show up. Is that a bug or does it just take a while for it to show up?

image

**Comment by glennsl** [comment]
Yeah, npms unfortunately died after fetching just the first package, and therefore screwed up the deployment. I thought it would be down for just a short bit, but ti hasn't come back up yet.

I should probably roll back. And handle errors better...

**Pull request merged**
