### PR TITLE
Remove neglected flag from bs-ant-design

### PR DESCRIPTION
**Pull request by thangngoc89**
I updated [bs-ant-design](https://github.com/thangngoc89/bs-ant-design) recently. Please check the new README

### CODE REVIEW

**Comment by glennsl** [comment]
Looks great! You need to also publish it for the changes to be picked up though. Let me know when you've done so.

**Comment by thangngoc89** [comment]
@glennsl I published it as bs-ant-design@1.1.0

**Comment by glennsl** [comment]
Thanks!

**Comment by thangngoc89** [comment]
Thank you !

**Pull request merged**
