### PR TITLE
add bs-storybook to sources.json

### PR DESCRIPTION
**Pull request by kgoggin**
Note: there's an existing `bs-storybook` in the redex, but it was never published to npm, and has been dormant for several months.

Thanks!

### CODE REVIEW

**Comment by glennsl** [comment]
Thanks, looks great! It could use some more direct installation instructions though. The exact command to isntall it, a link to the Storybook docs etc.

I also don't think it's a good idea to publish as just `bs-storybook` when there's an existing package with that name. That'll just cause confusion. Could you publish under your own name (scope) instead? That's recommended when publsihing in general anyway, but especially when there existing name conflicts that can cause confusion.

**Comment by glennsl** [comment]
Closing this due to unresponsiveness. Please reopen or resubmit when the above issues have been addressed. And feel free to ask any questions here if you have them, of course!

**Comment by kgoggin** [comment]
Yikes! Somehow I missed the notification about your original comment. Sorry about that. I went ahead and update the README to be a little more specific - is that what you had in mind?

As for the name, I agree it's not ideal. I'm also on the fence about scoped packages since it makes transferring ownership a little tricky and I'm not sure it's that much less confusing to have multiple packages out there with the same name but different scopes. I guess I'd also be more on board if the owner of the first project actually seemed to be maintaining it at all or had actually published it? In that case I probably would have just offered this up as a PR to their work, honestly, because I think everyone's best served by one set of bindings everyone's working on and improving together!

All that to say, I respectfully request to go ahead with it as is (unscoped), though I'm open to more debate on it if you feel that strongly about it.

**Comment by glennsl** [comment]
Alright, I con't really care enough to argue about it :). The README looks great, but could you publish the changes? Otherwise it won't get picked up.

**Comment by kgoggin** [comment]
@glennsl ah, that'd help :). Just published - thanks!

**Pull request merged**
