### PR TITLE
Add mailgun-js binding

### PR DESCRIPTION
**Pull request by piq9117**

### CODE REVIEW

**Comment by glennsl** [comment]
Hey. Could you add a usage example, a description of what mailgun.js does and a link to its repository to the readme?

**Comment by piq9117** [comment]
Thanks for the response @glennsl! I shouldn't have missed that since it was in the docs on how to publish to redex. I added a short description. However for the usage, can I have a link to the example usage to another markdown file coz it's quite long to display in the read me

**Comment by glennsl** [comment]
No worries :) It would be great to have an example of the most common and minimal use case in the readme itself, just to get an impression of what the API looks like right away. And then also provide a link to the other examples right above or below.

**Comment by glennsl** [comment]
Great! Will you do a patch release to get the changes into the published package? Then let me know and I'll merge this and rebuild redex.

**Comment by piq9117** [comment]
Yes sir. https://www.npmjs.com/package/@piq9117/bs-mailgun. I hope this is enough

**Comment by glennsl** [comment]
Looks great. Thanks!

**Comment by piq9117** [comment]
awesome! thanks for taking the time to do this.

**Pull request merged**
