### PR TITLE
Add bs-jest-dom

### PR DESCRIPTION
**Pull request by wyze**

### CODE REVIEW

**Comment by glennsl** [comment]
Cool, thanks! NPMS unfortunately haven't indexed packages for the past week, which means if I publish this now I'll publish version 1.0.0. Are you OK with that, or would you like me to wait until NPMS is back up? It's been down for a month before, so it might take a while.

**Comment by glennsl** [comment]
Perhaps the bs-jest readme should have a section for extension packages that links to this? What do you think?

Also, do you still have outstanding issues integrating with bs-jest that you think could be done better on that side?

**Comment by wyze** [comment]
> Perhaps the bs-jest readme should have a section for extension packages that links to this? What do you think?

I think that could be useful, but up to you if you want a section about custom/additional matchers.

> Also, do you still have outstanding issues integrating with bs-jest that you think could be done better on that side?

I don't know. I took your structure of `affirm` function and applied the same thing. Then wrapped that in the following:

```ocaml
let toJestAssertion = expected =>
  Jest.Expect.((() => expected)->Jest.Expect.expect->not_->toThrow);
```

So not sure if you can write a helper utility, or something else that would accept a function/function result of something like `affirm`.

Also, you on discord for a quick chat? :)

**Comment by glennsl** [comment]
> I think that could be useful, but up to you if you want a section about custom/additional matchers.
Alright, I'll add the section after this has been published.  Or if I forget, feel free to submit a PR.

> So not sure if you can write a helper utility, or something else that would accept a function/function result of something like affirm.

Hmm, doesn't this alter the error message that jest displays then?

**Comment by wyze** [comment]
> Hmm, doesn't this alter the error message that jest displays then?

Hard to say, but I think they are still decent.

```
    expect(element).toHaveStyle()

    - Expected

    - display: inline-block;
    + display: none;

      117 |         if (match$20[0] >= 826472012) {
      118 |           var match$21 = match$20[1];
    > 119 |           return expect(match$21[0]).toHaveStyle(match$21[1]);
          |                                      ^
      120 |         } else {
      121 |           var match$22 = match$20[1];
      122 |           return expect(match$22[0]).not.toHaveStyle(match$22[1]);

      at toHaveStyle (src/JestDom.bs.js:119:38)
      at Object.affirm [as toHaveStyle] (src/JestDom.bs.js:222:26)
      at toHaveStyle (src/__tests__/JestDom_test.bs.js:171:24)
```
```
  ● toHaveClass

    expect(element).toHaveClass("empty")

    Expected the element to have class:
      empty
    Received:
      empt

      92 |         if (match$13[0] >= 826472012) {
      93 |           var match$14 = match$13[1];
    > 94 |           return expect(match$14[0]).toHaveClass(match$14[1]);
         |                                      ^
      95 |         } else {
      96 |           var match$15 = match$13[1];
      97 |           return expect(match$15[0]).not.toHaveClass(match$15[1]);

      at toHaveClass (src/JestDom.bs.js:94:38)
      at Object.affirm [as toHaveClass] (src/JestDom.bs.js:191:26)
      at toHaveClass (src/__tests__/JestDom_test.bs.js:109:24)
```

**Comment by glennsl** [comment]
NPMS is back up, so I've now published it and added an [extensions section](https://github.com/glennsl/bs-jest#extensions) to bs-jest's readme

**Pull request merged**
