### PR TITLE
Added bs-rewire module

### PR DESCRIPTION
**Pull request by gmmorris**
Added the bs-rewire module which provides bindings for the Rewire unit testing utility

### CODE REVIEW

**Comment by glennsl** [comment]
Hey. There does not seem to be any npm package named `@gmmorris/bs-rewire` or just `bs-rewire`. You can list an unpublished package directly from github too, but would then have to move it to the `unpublished` section and fix the installation instructions.

**Comment by gmmorris** [comment]
Hey Glenn,
That was a mistake on the publishing which I already sorted earlier today. It should be good now!

**Comment by gmmorris** [comment]
Is this not loading for you?
https://www.npmjs.com/package/@gmmorris%2Fbs-rewire

**Comment by glennsl** [comment]
Hmm, it does, but I can't find it through search and it hasn't been picked up by npms. I'll put this on hold for 24hrs or so to see if it gets picked up. If it isn't by then, just pushing a new patch release will most likely fix it.

**Comment by gmmorris** [comment]
Weird. Wondering if I've somehow published it incorrectly. I don't usually publish scoped modules... I'll see if anything in the settings is funky.

**Comment by glennsl** [comment]
It's still not been picked up. You could try pushing a new patch release, or we can just wait and see for a bit longer.

**Comment by gmmorris** [comment]
I've sent a support ticket to Npm.
I'll get back to you when I hear from them.

No pressure on my end anyway 😊

Thanks

**Comment by glennsl** [comment]
Now it's been picked up. Thanks!

**Comment by gmmorris** [comment]
Awesome, thanks 😁

**Pull request merged**
