### PR TITLE
Add reason-date-fns

### PR DESCRIPTION
**Pull request by dmtrKovalenko**

### CODE REVIEW

**Comment by glennsl** [comment]
This isn't being picked up by NPMS for some reason. Will check back when I've heard from them.

**Comment by glennsl** [comment]
NPMS is back up! Unfortunately there's still a few issues with this:

1. There's no repository information in 'package.json'. This is needed to link back to the source code repository.

2. You've put this in the "prematurely-published" section, which I'm guessing was not intended. I can move it for you, but just wanted to confirm that you didn't mean anything in particular by that.

3. There are already bindings to `date-fns` on redex in the form `bs-date-fns`. Could you explain how this differs from that? Why do we need another one instead of a PR to the original?

**Comment by dmtrKovalenko** [comment]
## Differences from bs-date-fns

There are 2:
1) This project is exporting to `date-fns` of v2
2) And using `FP` submodule. So currying is enabled by default 😎

**Comment by glennsl** [comment]
Oh, I didn't scroll that far down, sorry :) I also feel like we've had this talk before for some reason. Anyway, the two other issues remain. Let me know when you've fixed them, then I can probably merge.

**Comment by dmtrKovalenko** [comment]
Closed in favor of #125

**Pull request closed without merging**
