### PR TITLE
Move vow to published

### PR DESCRIPTION
**Pull request by wokalski**

### CODE REVIEW

**Comment by glennsl** [comment]
Thanks! You forgot to update the instructions before publishing though :( I'll merge this anyway, but will hold off on rebuilding until you've fixed it (if you do it quick).

**Comment by wokalski** [comment]
I've fixed it. Can I republish to npm?

**Comment by glennsl** [comment]
Yes, and bump the version too unfortunately, or you'll not be allowed to publish

**Comment by wokalski** [comment]
Done. Thank you 👍

**Comment by glennsl** [comment]
You kind of missed a spot:

> Then add **`vow`** to `bs-dependencies` in your `bsconfig.json`

But I don't think that's very noticable since the example below is correct. I'll rebuild then.

**Pull request merged**
