### PR TITLE
Add bs-rsuite-ui-react bindings

### PR DESCRIPTION
**Pull request by shurygindv**
Hi! I would be to share rsuite-react-binding in your package indexes

### CODE REVIEW

**Comment by glennsl** [comment]
Thanks! Unfortunately a third-party service we rely on is down right now, and has been for a few months. I think we have to transition away from it, which will also take some time. In any case, I'll have to get back to this, and it might take a while but I'll keep this open and waiting until then.

**Comment by shurygindv** [comment]
@glennsl , Could I (we) help something with it? I would be glad!! I've noticed its problem since July (by similar with other `pull requests`)

**Comment by glennsl** [comment]
Thanks for offering! And there is! In the short term we can get redex up and going again, barring a few features, by rewriting some scripts to use the NPM API instead of the NPMS API. See https://github.com/redex/redex-scripts/issues/1. I'll post a more detailed explanation there.

**Comment by glennsl** [comment]
NPMS is back up, so good to merge!

If you'd still like to help it would still be useful to have NPM as backup though. NPMS was down for several months, and will most likely go down again for an extended time.

**Pull request merged**
