### PR TITLE
added @idkjs/reason-expo-vector-icons

### PR DESCRIPTION
**Pull request by idkjs**

### CODE REVIEW

**Comment by glennsl** [comment]
Thanks. NPMS is down I'm afraid, and has been for a while unfortunately, so I can't merge anything for the moment. I'll get back to this once it's up and running again.

**Comment by idkjs** [comment]
Thanks you.

**Comment by idkjs** [comment]
didnt mean to cloe.

**Comment by glennsl** [comment]
Hey. NPMS is back up, but I just noticed there's already an existing package for this, which you seem to have forked and republished. Could you explain why you've done that rather than submit a pull request to the original repository? I couldn't find anything about it in the Readme, other than a credit to the original author.

**Comment by idkjs** [comment]
Hey boss, I think i put it in the readme that i tried to update the icons and jsx on that project then ended up with a slightly different api. At any rate, I mostly did it to use in some projects and figured i would learn how to publish a package to npm. Its not at all necessary to publish on redex, especially if the other package has been updated which it may very well have by now. Why don't i just withdraw this request. No need to publish. Thank you for all you do, and for this note, brother. That stackoverflow HOC post is something i go back to all the time. 
Peace to you.

**Pull request closed without merging**
