### PR TITLE
Add bs-sql-common, bs-sql-composer

### PR DESCRIPTION
**Pull request by scull7**
https://github.com/scull7/bs-sql-common
https://github.com/scull7/bs-sql-composer

### CODE REVIEW

**Comment by glennsl** [comment]
Awesome, looks great! A few niggles about `bs-sql-common` though, the readme title says `bs-sql-wrapper` and there's no installation section. You also don't need to prvoide both reason and ocaml examples for redex as it'll auto-translate them (and you'll know get duplicate examples). Though if you want to have both on github or npm, you'll have to do so, of course.

Let me know when you've addressed htese, then I'll merge.

**Comment by scull7** [comment]
Should I just include the ReasonML examples then? Since most people will be looking for that?

**Comment by scull7** [comment]
@glennsl I removed the OCaml examples, corrected the name and added an installation section.

**Comment by glennsl** [comment]
Great! you need to publish the changes too though, or it won't get picked up ;)

**Comment by scull7** [comment]
Published the latest changes to npm (v0.7.2)

**Comment by glennsl** [comment]
Thanks!

**Pull request merged**
