### PR TITLE
Update sources.json

### PR DESCRIPTION
**Pull request by Acciaiodigitale**
Added Fastify bindings package

### CODE REVIEW

**Comment by glennsl** [comment]
Thanks! This is missing the repository url in package.json though. It would also be great to have a usage example in the Readme. Do you think you could add that?

**Comment by Acciaiodigitale** [comment]
Hi. There is an example dir. I write the docs in the wiki on GitHub soon.
Wait only a couple of day. And I correct the submission and complete the
missing things.
Thanks!

Il giorno ven 18 gen 2019, 20:47 Glenn Slotte <notifications@github.com> ha
scritto:

**Comment by glennsl** [comment]
No problem. Even with examples and documentation on other pages, I think having a usage example on the frontpage is very helpful in giving a good first impression. You can glean a lot of information about a library from just a simple example. If you look around on redex you'll see almost every package has a usage example up front.

**Comment by Acciaiodigitale** [comment]
Ok thanks for the suggestion. I'll do it

Il giorno ven 18 gen 2019, 21:02 Glenn Slotte <notifications@github.com> ha
scritto:

**Comment by Acciaiodigitale** [comment]
Hi @glennsl.
I just published on npm v0.1.4 wiyh your suggestion:
- package.json with repository url (and me as contributor lol) 
- example (and benchmark) on Readme
Thanks for your advice!

**Comment by glennsl** [comment]
Looks good. Thanks!

**Pull request merged**
