### PR TITLE
add reason-xstream

### PR DESCRIPTION
**Pull request by italonascimento**
Just adding the xstream binding I've created.

It's published at https://www.npmjs.com/package/reason-xstream.

The docs are available on the repo readme: https://github.com/italonascimento/reason-xstream

### CODE REVIEW

**Comment by glennsl** [comment]
Hey. There's already some xstream bindings on redex, [@j3a/bs-xstream](https://redex.github.io/package/@j3a/bs-xstream) (added just a few weeks ago actually). Could you explain how your bindings differ from those, and if it does not in any significant way, could you try to work with @j3a on consolidating the bindings?

**Comment by italonascimento** [comment]
Not sure about the implementation's differences, even though it's clearly implemented in a different way. There wasn't other bindings on npm when I made mine, but I didn't submit to redex, so I haven't seen this other repo until now.

I guess there's a usage difference, and a more extensive documentation on my repo. But if you think it would be better no to list both packages in here, I'll understand.

**Comment by glennsl** [comment]
I don't mind listing multiple bindings to the same library, as long as it's easy for consumers to choose between them. And if you, who wrote one the bindings, can't figure out the difference, how should those with much less knowledge of the domain be able to?

I think there's two options for moving forward here: Either there's a good reason to have a second set of bindings, and as long that reason is explained clearly in the README (or is otherwise obvious) I'd be happy to list both. If there is not a good reason, but perhaps some minor aspects that are better in one or the other, I suggest you talk to the author of the other bindings to see if you might be able to consolidate them to make one set of bindings that are better than each of them separately.

**Comment by italonascimento** [comment]
That seems a good way to proceed. I'll take a look at this other repo to understand his implementation choices, and then I'll get back here.

**Comment by glennsl** [comment]
Spring cleanup. Feel free to reopen when the issues have been addressed.

**Pull request closed without merging**
