### PR TITLE
add react-native-modal

### PR DESCRIPTION
**Pull request by broerjuang**
Binding of [react-native-modal](https://www.npmjs.com/package/bs-react-native-modal)

### CODE REVIEW

**Comment by glennsl** [comment]
Hey, Your package hasn't been picked up by npms yet. Could you try doing a patch version bump and republish it?

**Comment by broerjuang** [comment]
Sure, will do it!

**Comment by broerjuang** [comment]
It's been done [https://www.npmjs.com/package/bs-react-native-modal](here)

**Comment by glennsl** [comment]
Hmm, still not. It seems NPMS has bigger issues. We'll just have to wait until they get it sorted

**Comment by glennsl** [comment]
NPMS fixed. Thanks!

**Pull request merged**
